markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Sleepless in Sydney"
markdown: rdiscount

author: "Meredith"
atom-baseurl: "http://sleeplessinsydney.com"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

