markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Data Geek"
markdown: kramdown

author: "Norris"
atom-baseurl: "http://norris-niu.top"
disqus: "Norris New"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Tools
    class: fa fa-film
    href: /tool.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

