name: "rusty shutter"
permalink: /:year/:month/:day/:title.html

author: "wayne"
atom-baseurl: "http://lhzhang.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fas fa-list-ul
    href: /archive.html
  - title: Tags
    class: fas fa-tags
    href: /tags.html
  - title: About
    class: fas fa-user
    href: /about.html
  - title: Osara
    class: far fa-dot-circle
    href: https://osara.lhzhang.com
  - title: Gallery
    class: fas fa-film
    href: http://foto.lhzhang.com
  - title: Subscribe
    class: fas fa-rss
    href: /atom.xml
